### PR TITLE
Fixes web compilation error for Flutter 3.7.0

### LINKED ISSUE #15: Can't compile project for web using with Flutter 3.7.0
Can't compile my project for web using `flutter build web` with Flutter 3.7.0

```
../../../../.pub-cache/hosted/pub.dev/rich_clipboard_web-1.0.1/lib/rich_clipboard_web.dart:114:12: Error: `@staticInterop` classes should not contain any generative constructors.
Use factory constructors instead.
  external _ClipboardItem(dynamic args);
           ^
```

### PR DESCRIPTION
**Pull request by BirjuVachhani**
Fixes [#15](https://github.com/BringingFire/rich_clipboard/issues/15)

### CODE REVIEW

**Review by jmatth — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by BirjuVachhani** [comment]
@jmatth Thanks. Please let me know once this lands on pub.dev. Right now I am using a fork!

**Comment by jmatth** [comment]
[It's already published.](https://pub.dev/packages/rich_clipboard_web/changelog#102)

**Comment by BirjuVachhani** [comment]
Ah! I see. Thanks.

**Pull request merged**
